[BTAT-8025] Scala/SBT 2.12/1.3 upgrade
hmrc/vat-correspondence-details-frontend pull request #242
Opened 2020-09-08 15:19 UTC by daparkes

2020-09-08 15:22 UTC, daparkes commented
Please also merge https://github.com/hmrc/build-jobs/pull/6490
and https://github.com/hmrc/service-manager-config/pull/2564

2020-09-10 13:48 UTC, JoNB7777 requested changes

2020-09-10 13:48 UTC, JoNB7777 commented on project/build.properties
> -sbt.version=0.13.18
There is a later version available (1.3.13)

2020-09-10 15:57 UTC, JoNB7777 approved these changes

2020-09-11 09:46 UTC, merged